-- Enable Row Level Security (RLS) on all public tables
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Workflow" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkflowVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Conversation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ConversationMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExportHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "subscription_plans" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Subscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Invoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApiKey" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "internal_graphs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workflow_planning_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workflow_patterns" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workflow_execution_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workflow_success_patterns" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workflow_drafts" ENABLE ROW LEVEL SECURITY;